import { db } from "./db";
import { agents, llmTxtConfigs, agentApiKeys, agentApiUsage } from "@shared/schema";
import { eq, and, sql, desc } from "drizzle-orm";
import crypto from "crypto";

export interface LLMTxtConfig {
  id: number;
  agentId: number;
  enabled: boolean;
  title: string;
  description: string;
  instructions: string;
  citationFormat: string;
  allowedMethods: string[];
  rateLimit: number;
  accessLevel: 'public' | 'authenticated' | 'paid';
  pricePerRequest: number;
  customRules: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface AgentApiKey {
  id: number;
  agentId: number;
  keyName: string;
  keyHash: string;
  keyPrefix: string;
  accessLevel: 'read' | 'write' | 'admin';
  rateLimit: number;
  expiresAt?: Date;
  isActive: boolean;
  createdAt: Date;
}

export interface AgentApiUsage {
  id: number;
  agentId: number;
  apiKeyId: number;
  requestorAgentId?: number;
  method: string;
  endpoint: string;
  responseCode: number;
  tokensUsed: number;
  cost: number;
  timestamp: Date;
}

export class LLMTxtService {
  /**
   * Generate llm.txt content for an agent
   */
  async generateLLMTxt(agentId: number): Promise<string> {
    const config = await this.getLLMTxtConfig(agentId);
    if (!config || !config.enabled) {
      return this.generateDefaultLLMTxt(agentId);
    }

    const agent = await db.select()
      .from(agents)
      .where(eq(agents.id, agentId))
      .limit(1);

    if (agent.length === 0) {
      throw new Error("Agent not found");
    }

    const agentData = agent[0];

    let llmTxt = `# LLM.txt for ${config.title}\n\n`;
    llmTxt += `## Agent Information\n`;
    llmTxt += `- Name: ${agentData.name}\n`;
    llmTxt += `- Category: ${agentData.category}\n`;
    llmTxt += `- Description: ${config.description}\n`;
    llmTxt += `- Model: ${agentData.model}\n`;
    llmTxt += `- Voice Enabled: ${agentData.voiceEnabled ? 'Yes' : 'No'}\n`;
    llmTxt += `- Image Generation: ${agentData.imageEnabled ? 'Yes' : 'No'}\n\n`;

    llmTxt += `## AI Interaction Instructions\n`;
    llmTxt += `${config.instructions}\n\n`;

    llmTxt += `## Citation Format\n`;
    llmTxt += `${config.citationFormat}\n\n`;

    llmTxt += `## API Access\n`;
    llmTxt += `- Access Level: ${config.accessLevel}\n`;
    llmTxt += `- Rate Limit: ${config.rateLimit} requests/hour\n`;
    llmTxt += `- Allowed Methods: ${config.allowedMethods.join(', ')}\n`;
    
    if (config.accessLevel === 'paid') {
      llmTxt += `- Price per Request: $${config.pricePerRequest.toFixed(4)}\n`;
    }

    llmTxt += `\n## Available Endpoints\n`;
    llmTxt += `- GET /api/agents/${agentId}/llm.txt - This file\n`;
    llmTxt += `- POST /api/agents/${agentId}/interact - Chat with agent\n`;
    llmTxt += `- GET /api/agents/${agentId}/info - Agent information\n`;
    
    if (config.allowedMethods.includes('memory')) {
      llmTxt += `- GET /api/agents/${agentId}/memory - Access agent memories (auth required)\n`;
    }

    if (config.customRules) {
      llmTxt += `\n## Custom Rules\n`;
      llmTxt += `${config.customRules}\n`;
    }

    llmTxt += `\n## Authentication\n`;
    if (config.accessLevel === 'public') {
      llmTxt += `No authentication required for basic interaction.\n`;
    } else if (config.accessLevel === 'authenticated') {
      llmTxt += `Requires valid API key. Contact agent owner for access.\n`;
    } else if (config.accessLevel === 'paid') {
      llmTxt += `Requires paid API key. Contact agent owner for pricing and access.\n`;
    }

    llmTxt += `\n## Rate Limiting\n`;
    llmTxt += `All endpoints are subject to rate limiting. Current limit: ${config.rateLimit} requests per hour.\n`;

    llmTxt += `\n---\n`;
    llmTxt += `Generated by ShareBrain AI Agent Platform\n`;
    llmTxt += `Last Updated: ${new Date().toISOString()}\n`;

    return llmTxt;
  }

  /**
   * Get LLM.txt configuration for an agent
   */
  async getLLMTxtConfig(agentId: number): Promise<LLMTxtConfig | null> {
    const configs = await db.select()
      .from(llmTxtConfigs)
      .where(eq(llmTxtConfigs.agentId, agentId))
      .limit(1);

    return configs[0] || null;
  }

  /**
   * Create or update LLM.txt configuration
   */
  async updateLLMTxtConfig(agentId: number, userId: string, config: Partial<LLMTxtConfig>): Promise<LLMTxtConfig> {
    // Verify agent ownership
    const agent = await db.select()
      .from(agents)
      .where(and(eq(agents.id, agentId), eq(agents.userId, userId)))
      .limit(1);

    if (agent.length === 0) {
      throw new Error("Agent not found or access denied");
    }

    const existingConfig = await this.getLLMTxtConfig(agentId);
    
    if (existingConfig) {
      // Update existing config
      const [updated] = await db.update(llmTxtConfigs)
        .set({
          ...config,
          updatedAt: new Date()
        })
        .where(eq(llmTxtConfigs.agentId, agentId))
        .returning();
      
      return updated;
    } else {
      // Create new config
      const [created] = await db.insert(llmTxtConfigs)
        .values({
          agentId,
          enabled: config.enabled ?? true,
          title: config.title ?? agent[0].name,
          description: config.description ?? (agent[0].description || ""),
          instructions: config.instructions ?? "You may interact with this agent following standard AI ethics guidelines.",
          citationFormat: config.citationFormat ?? `Source: ${agent[0].name} AI Agent via ShareBrain`,
          allowedMethods: config.allowedMethods ?? ['chat', 'info'],
          rateLimit: config.rateLimit ?? 100,
          accessLevel: config.accessLevel ?? 'public',
          pricePerRequest: config.pricePerRequest ?? 0,
          customRules: config.customRules ?? "",
          createdAt: new Date(),
          updatedAt: new Date()
        })
        .returning();

      return created;
    }
  }

  /**
   * Generate API key for an agent
   */
  async generateApiKey(agentId: number, userId: string, keyName: string, accessLevel: 'read' | 'write' | 'admin' = 'read'): Promise<{ key: string; keyData: AgentApiKey }> {
    // Verify agent ownership
    const agent = await db.select()
      .from(agents)
      .where(and(eq(agents.id, agentId), eq(agents.userId, userId)))
      .limit(1);

    if (agent.length === 0) {
      throw new Error("Agent not found or access denied");
    }

    // Generate API key
    const apiKey = `sbag_${crypto.randomBytes(32).toString('hex')}`;
    const keyHash = crypto.createHash('sha256').update(apiKey).digest('hex');
    const keyPrefix = `sbag_${apiKey.slice(5, 13)}...`;

    const [keyData] = await db.insert(agentApiKeys)
      .values({
        agentId,
        keyName,
        keyHash,
        keyPrefix,
        accessLevel,
        rateLimit: 1000, // Default rate limit
        isActive: true,
        createdAt: new Date()
      })
      .returning();

    return { key: apiKey, keyData };
  }

  /**
   * Validate API key and record usage
   */
  async validateApiKey(apiKey: string, agentId: number, method: string, endpoint: string): Promise<{ valid: boolean; keyData?: AgentApiKey; cost?: number }> {
    const keyHash = crypto.createHash('sha256').update(apiKey).digest('hex');
    
    const keys = await db.select()
      .from(agentApiKeys)
      .where(and(
        eq(agentApiKeys.keyHash, keyHash),
        eq(agentApiKeys.agentId, agentId),
        eq(agentApiKeys.isActive, true)
      ))
      .limit(1);

    if (keys.length === 0) {
      return { valid: false };
    }

    const keyData = keys[0];

    // Check if key is expired
    if (keyData.expiresAt && keyData.expiresAt < new Date()) {
      return { valid: false };
    }

    // Check rate limit (simple hourly check)
    const oneHourAgo = new Date(Date.now() - 60 * 60 * 1000);
    const usage = await db.select({ count: sql`count(*)` })
      .from(agentApiUsage)
      .where(and(
        eq(agentApiUsage.apiKeyId, keyData.id),
        sql`${agentApiUsage.timestamp} > ${oneHourAgo}`
      ));

    const currentUsage = Number(usage[0].count);
    if (currentUsage >= keyData.rateLimit) {
      return { valid: false };
    }

    // Get pricing from LLM config
    const config = await this.getLLMTxtConfig(agentId);
    const cost = config?.pricePerRequest || 0;

    return { valid: true, keyData, cost };
  }

  /**
   * Record API usage
   */
  async recordApiUsage(agentId: number, apiKeyId: number, method: string, endpoint: string, responseCode: number, tokensUsed: number = 0, cost: number = 0, requestorAgentId?: number): Promise<void> {
    await db.insert(agentApiUsage)
      .values({
        agentId,
        apiKeyId,
        requestorAgentId,
        method,
        endpoint,
        responseCode,
        tokensUsed,
        cost,
        timestamp: new Date()
      });
  }

  /**
   * Get API usage statistics
   */
  async getApiUsageStats(agentId: number, userId: string): Promise<any> {
    // Verify agent ownership
    const agent = await db.select()
      .from(agents)
      .where(and(eq(agents.id, agentId), eq(agents.userId, userId)))
      .limit(1);

    if (agent.length === 0) {
      throw new Error("Agent not found or access denied");
    }

    const usage = await db.select()
      .from(agentApiUsage)
      .where(eq(agentApiUsage.agentId, agentId))
      .orderBy(desc(agentApiUsage.timestamp));

    return usage;
  }

  /**
   * Generate default LLM.txt for agents without custom config
   */
  private async generateDefaultLLMTxt(agentId: number): Promise<string> {
    const agent = await db.select()
      .from(agents)
      .where(eq(agents.id, agentId))
      .limit(1);

    if (agent.length === 0) {
      throw new Error("Agent not found");
    }

    const agentData = agent[0];

    let llmTxt = `# LLM.txt for ${agentData.name}\n\n`;
    llmTxt += `## Agent Information\n`;
    llmTxt += `- Name: ${agentData.name}\n`;
    llmTxt += `- Category: ${agentData.category}\n`;
    llmTxt += `- Description: ${agentData.description || 'No description provided'}\n\n`;

    llmTxt += `## AI Interaction Instructions\n`;
    llmTxt += `This agent uses standard AI interaction protocols. Please follow general AI ethics guidelines when interacting.\n\n`;

    llmTxt += `## Citation Format\n`;
    llmTxt += `Source: ${agentData.name} AI Agent via ShareBrain\n\n`;

    llmTxt += `## API Access\n`;
    llmTxt += `- Access Level: public\n`;
    llmTxt += `- Rate Limit: 100 requests/hour\n`;
    llmTxt += `- Available Methods: chat, info\n\n`;

    llmTxt += `## Available Endpoints\n`;
    llmTxt += `- GET /api/agents/${agentId}/llm.txt - This file\n`;
    llmTxt += `- POST /api/agents/${agentId}/interact - Chat with agent\n`;
    llmTxt += `- GET /api/agents/${agentId}/info - Agent information\n\n`;

    llmTxt += `---\n`;
    llmTxt += `Generated by ShareBrain AI Agent Platform\n`;
    llmTxt += `Last Updated: ${new Date().toISOString()}\n`;

    return llmTxt;
  }
}

export const llmTxtService = new LLMTxtService();